
services:
  mcp-server:
    build:
      context: ./MCPServer
    ports:
      - "8000:8000"
  env-agent:
    build:
      context: ./ENV_Agent
    ports:
      - "8008:8008"
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000/sse
    depends_on:
      - mcp-server
  # speech-to-text-module:
  #   build: 
  #     context: ./SpeechToTextModule
  #   ports:
  #     - "3000:3000"

    
